### Create Account
PUT {{url}}/accounts
Content-Type: application/json

{
  "owner": "lixia",
  "currency": "USD"
}

### Get Account
GET {{url}}/accounts/1

### Get Accounts
### page_id: 页数
### page_size: 每页返回的数量
GET {{url}}/accounts?page_id=2&page_size=5
